-- ============================================================================
-- DEPRECATED — do not run.
--
-- This single-file prototype schema has been superseded by the versioned
-- migrations in `supabase/migrations/`. Apply those instead:
--
--   supabase db reset           # local: replays all migrations + seed.sql
--   supabase db push            # remote: applies pending migrations
--
-- See `supabase/README.md` for setup and the admin bootstrap step.
-- This file is kept only to avoid breaking any external references and will be
-- removed in a future cleanup.
-- ============================================================================
